# Generated by Django 3.2.9 on 2021-11-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('NbParts', models.CharField(choices=[('0', '0-3'), ('1', '4-14'), ('2', '15-25'), ('3', '25-64'), ('4', 'Plus de 65')], default='2', max_length=10)),
                ('MotMairie', models.BooleanField()),
                ('CarteDonnee', models.BooleanField()),
                ('PresenceDistribution', models.BooleanField()),
                ('Remarque', models.CharField(max_length=255)),
            ],
        ),
    ]
