# Generated by Django 3.2.9 on 2021-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='address',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='CarteDonnee',
            new_name='carteDonnee',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='MotMairie',
            new_name='motMairie',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='NbParts',
            new_name='nbParts',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='PresenceDistribution',
            new_name='presenceDistribution',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='Remarque',
            new_name='remarque',
        ),
        migrations.RenameField(
            model_name='beneficiaire',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='validated',
            field=models.BooleanField(default=0),
        ),
    ]
