# Generated by Django 3.2.9 on 2021-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='remarque',
            field=models.TextField(max_length=255),
        ),
    ]
