# Generated by Django 3.2.9 on 2021-11-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_beneficiaire_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='remarque',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
