# Generated by Django 3.2.9 on 2021-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_beneficiaire_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaire',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
